server:
  port: 8091

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankstream
    username: bankstream
    password: bankstream
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092,localhost:29094
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Switch from JsonDeserializer to KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        # Schema Registry URL — consumer fetches schema by ID from here
        schema.registry.url: http://localhost:8081
        # Use specific Avro generated classes instead of GenericRecord
        # With true: deserializes to TransactionInitiatedEvent (generated class)
        # With false: deserializes to GenericRecord (generic map-like object)
        specific.avro.reader: true
        # Package where generated Avro classes live
        # Consumer uses this to find the right class for each schema
        spring.json.trusted.packages: "*"
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.bankstream: DEBUG
    org.apache.kafka: WARN